version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: todo_app_postgres
    environment:
      POSTGRES_DB: todo_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo_app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
